# Weights and biases
wandb_run: False

# Random seed
seed: None

# Directory structure
base_dir: ../LMH_HOPPL # NOTE: This path should be relative to the daphne path
daphne_dir: ../daphne  # NOTE: This path should be relative to the repository path

# Parameters
recursion_limit: 5000

# Tests and programs to run
deterministic_tests: []
hoppl_deterministic_tests: []
probabilistic_tests: []
homework4_programs: []
homework5_programs: []
homework6_programs: [7]

# Inference method
# inference: None
# inference: IS
# inference: SMC
inference: LMH
# inference: PSMC

# Compilation
compile: False

# Inference stuff
num_samples: 1e4
num_preconds: 2
tmax: 60 # Seconds