# Weights and biases
wandb_run: False

# Random seed
seed: None

# Directory structure
base_dir: ../LMH_HOPPL # NOTE: This path should be relative to the daphne path
daphne_dir: ../daphne  # NOTE: This path should be relative to the repository path

# Parameters
recursion_limit: 5000

# Tests and programs to run
deterministic_tests: []
hoppl_deterministic_tests: []
probabilistic_tests: []
homework4_programs: []
homework5_programs: []
homework6_programs: [4]

# Inference method
# inference: None
# inference: IS
# inference: SMC
# inference: LMH
# inference: PSMC
# inference: rejSMC
# inference: postSMC
inference: [SMC]

# Compilation
compile: False

# Inference stuff
num_samples: 1e4
# num_rej_run: [1, 15, 30, 45, 60, 75, 90, 105, 130]
num_rej_run: [1]
# num_samples_run: [1e2, 3e2, 5e2, 7e2, 9e2, 1.1e3, 1.3e3, 1.5e3, 1.7e3, 1.9e4, 2.1e4, 2.4e4, 2.7e4, 3e5]
#################   5    7.6   11.2  15.4   21.33   27.64   34
# num_samples_run: [1.5e2, 7e2, 1.3e3,  2e3,  2.7e3,  3.7e3, 4.9e3] # pre rej
# num_samples_run: [2e3, 3.5e3, 5e3, 7e3,  9e3, 1.2e4, 1.5e4] # regular smc
num_samples_run: [7e3, 1.5e4, 2.2e4, 3e4, 3.7e4, 4.2e4, 5e4]
# num_samples_run: [1.5e2,  2e3,  2.8e3,  5e3, 7.1e3, 10e3, 13e3] # post rej
# num_samples_run: [3e2,  5e2, 7.3e2, 10e2, 14e2] # post rej
# num_samples_run: [6e2, 1.3e3, 1.8e3, 2.4e3, 3.3e3, 3.7e3, 5e3] # pre rej
#################


# EXP setup
# num_samples_run: [1e3, 3.6e3, 6.5e3, 9.8e3, 1.2e4, 1.46e4, 1.8e4] # 1 push
# num_samples_run: [0.8e3, 3.2e3, 5.8e3, 7.8e3, 9.9e3, 1.25e4, 1.5e4] # 2 pushes
# num_samples_run: [0.5e3, 1.9e3, 3e3, 5e3, 7.2e3, 9.2e3, 1.3e4] # 2 pushes


# num_samples_run: [1e3]x


tmax: [60] # Seconds