# Weights and biases
wandb_run: False

# Random seed
seed: None

# Directory structure
base_dir: ../LMH_HOPPL # NOTE: This path should be relative to the daphne path
daphne_dir: ../daphne  # NOTE: This path should be relative to the repository path

# Parameters
recursion_limit: 5000

# Tests and programs to run
deterministic_tests: []
hoppl_deterministic_tests: []
probabilistic_tests: []
homework4_programs: []
homework5_programs: []
homework6_programs: [4]

# Inference method
# inference: None
# inference: IS
# inference: SMC
# inference: LMH
# inference: PSMC
# inference: rejSMC
inference: [rejSMC]

# Compilation
compile: False

# Inference stuff
num_samples: 1e4
# num_rej_run: [1,1,1,1,1,1,1,1,1,1]
# num_rej_run: [0,0,0,0,0,0,0,0,0,0]
num_rej_run: [1]
# num_samples_run: [1e2, 3e2, 5e2, 7e2, 9e2, 1.1e3, 1.3e3, 1.5e3, 1.7e3, 1.9e4, 2.1e4, 2.4e4, 2.7e4, 3e5]
# num_samples_run: [1e2, 4.6e2, 7.8e2, 1.2e3, 1.5e3, 1.98e3, 2.3e3]
# num_samples_run: [3e3, 9e3, 1.5e4, 2.1e4, 2.7e4, 3.3e4, 3.9e4]
# num_samples_run: [1e3, 3.6e3, 6.5e3, 9.8e3, 1.2e4, 1.46e4, 1.8e4] # 1 push
# num_samples_run: [0.8e3, 3.2e3, 5.8e3, 7.8e3, 9.9e3, 1.25e4, 1.5e4] # 2 pushes

num_samples_run: [1e4]


tmax: [60] # Seconds